version: "3.1"
services:
    db:
        image: mysql:8.2.0
        ports: 
            - 127.0.0.1:3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: alumne
            MYSQL_PASSWORD: alumne123
            MYSQL_DATABASE: alumne_db
            MYSQL_ROOT_PASSWORD: XQ0hbRisrWHo4w9
        volumes:
            # - ./sql:/docker-entrypoint-initdb.d
            # - ./conf:/etc/mysql/conf.d
            - mysql-data:/var/lib/mysql
    www:
        build:
            context: .
            dockerfile: apache.Dockerfile
        ports: 
            - 127.0.0.1:8080:80
        volumes:
            - ./php:/var/www/html
        links:
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        links: 
            - db:db
        ports:
            - 127.0.0.1:8081:80
volumes:
    mysql-data:
